# Generated by Django 5.1.6 on 2025-05-08 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='decorative_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
