# Generated by Django 5.1.6 on 2025-05-08 12:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogindexpage_decorative_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='cta_richtext',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
