# Generated by Django 5.1.6 on 2025-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogindexpage_cta_richtext_blogindexpage_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='cta',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
