# Generated by Django 5.1.6 on 2025-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectindexpage',
            old_name='summary',
            new_name='intro',
        ),
    ]
