# Generated by Django 5.1.6 on 2025-05-08 10:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projecttagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='decorative_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
