# Generated by Django 5.1.6 on 2025-05-08 10:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectpage_decorative_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='decorative_title',
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='decorative_title',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
