# Generated by Django 5.1.6 on 2025-05-08 11:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_projectpage_decorative_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='cta_richtext',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
