# Generated by Django 5.1.6 on 2025-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectindexpage_cta_richtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectindexpage',
            name='cta_richtext',
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='cta',
            field=models.CharField(default='voir', max_length=128),
            preserve_default=False,
        ),
    ]
