# Generated by Django 5.1.6 on 2025-05-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_projectindexpage_cta_richtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='cta',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
