# Generated by Django 5.1.6 on 2025-05-08 12:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resdigita', '0002_pagehome_hero_cta_pagehome_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehome',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagehome',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
